### ISSUE TITLE
MongoDB Timeout causing server to crash.

### ISSUE THREAD

**Issue by Ronski0** [Romitou/MongoSK#9]
I run a pretty popular minehut server (DawnGN), We are the first server to use MongoSK afaik, And it isn't going so smoothly. We've had several crashes due to the same error ("MongoTimeoutException"), And I was wondering if this is getting fixed or it's user error? Thanks!

[message (4).txt](https://github.com/Romitou/MongoSK/files/5748023/message.4.txt)

**Comment by Romitou** [comment]
Hello, thank you for reporting this problem.

In my experience and at first sight, this is a problem other than that of the MongoDB driver. Try to check with your cluster host to make sure that the sockets are not disconnected after a certain time of inactivity. I may be wrong here, but I think it is a user problem.

However, this issue brings me two more problems. The MongoDB client makes wait 30 seconds while mobilizing the main thread, which causes the whole server to crash.

So I'm thinking of adding more user connection options, such as the heart beat frequency, the sockets timeout and more. Hopefully the support for changing these values will solve your problem.

I still mark this issue as a bug, feel free to tell me more if you have more information.
Thank you!

**Comment by Ronski0** [comment]
Thanks for the quick response, Not trying to be in a hurry but when do you think this bug will get fixed? The crashes caused my playerbase to basically disappear (We were averaging 40+ yesterday), And I use MongoDB to have discord & minecraft linking. And I don't think it'd be user error since I have a discord bot that uses MongoDB for coins / suggestions / reactionroles / ticketing and it doesn't get affected whatsoever.

**Comment by Romitou** [comment]
After several checks and having tested directly at Minehut, I didn't find any problems, everything was working normally. Unfortunately I can't replicate this problem so I don't have enough information to investigate what's going on.

However, try to add these arguments to your connection address: `?retryWrites=true&w=majority`. If this doesn't change anything, can you send me a test script so that I can try to replicate the problem again?

Please also contact your Minecraft host and Mongo host to make sure that everything works at the network level and that the sockets are not disconnected. I am currently working on adding more connection options in the hope that this could potentially solve your problem.

Cheers!

**Comment by Ronski0** [comment]
This is my current connection addr: "mongodb+srv://redacted:redacted@redacted.ptwun.mongodb.net/redacted?retryWrites=true&w=majority". I have contacted Minehut yesterday about what could be the cause and they said that networking on their side is fine, And I've looked at my cluster's status and it seems to be fine on MongoDB's end too. This is the Skript that's been causing the issues: https://pastebin.com/5utKTr7X

I'm not running it on DawnGN for now as it has killed / ruined this season.

**Comment by Romitou** [comment]
Okay, I've just used your script under different environments (personal machine, a Minecraft host and on my VPS) with Skript 2.5.3 and MongoSK 1.1.0, trying each time a different MongoDB server. I didn't encounter any problems.

However after some research of your problem, I redirect you towards this [article](https://docs.mongodb.com/manual/faq/diagnostics/#does-tcp-keepalive-time-affect-mongodb-deployments) which should help you to solve the problem on your side. Indeed and I agree with you, it is preferable to avoid using MongoDB if you have problems with it.

I close this issue, if you have other information on this subject, do not hesitate to reply. If other people have this problem, do not hesitate to reply or open another issue in order to have more information on this problem.
Cheers
